### ISSUE TITLE
Recent Krunker Update fucked krunker APIs

### ISSUE THREAD

**Issue by Xyrrm** [fasetto/krunker.io#9]
**Describe the bug**
You prob already know the most recent Krunker update completely fucked all krunker APIs

**To Reproduce**
1. Get anything with the API

**Expected behavior**
Returns Correct data

**Additional context**

**Comment by fasetto** [comment]
Thanks for reporting. 
I am not aware of that, not actively working on this project but I will fix later when I have time to deal with it.
In the meantime other people are welcome to help me with this. 🙏

**Comment by Xyrrm** [comment]
Websockets were updated to wss://social.krunker.io/ws

**Comment by histefanhere** [comment]
@Xyrrm both `wss://social.krunker.io/ws` and the websocket url that the module already uses (`wss://krunker_social.krunker.io/ws`) do not work, the issue lies somewhere else

**Comment by histefanhere** [comment]
I've tracked down the error! It looks like Krunker tweaked the format of the websocket data it expects to receive, and then also the format of the data it returns. Where previously we were sending `[ "r", [ "clan", clanName, null, null] ]`, now we just send `[ "r", "clan", clanName, null, null]`. Same goes for GetProfile and GetLeaderboard.

**Comment by fasetto** [comment]
If you guys have a working solution maybe you can contribute the project by making a PR.
Then I can merge and update the npm package.
